#Problem 8: Translating RNA into Protein
#Given: An RNA string s corresponding to a strand of mRNA (of length at most 10 kbp).
#Return: The protein string encoded by s.

mRNA_string_s = "AUGCAGGGUAUUGGCGGCUUAAUUCGCCACAAGUCCAAAUGUGGAUCAGCUUUCCAUAGACGUAGUUACCUGAAUUGUAACUCGAGCGAAAUCACCGUGCAGCCGCAUAAGCUUUCUAUUGUGUUCGUUCAUGAGAUAAGCAGGUUAUUUAAUAGCAUCCAUCCCGCUAUAAGGCUAUAUGGAGGCGCCCUCGAGAACGGCGUGUAUGGCCCGCGCAGCGGGUGUUCCAGCGGGCUUAUACAUAUCAAGAACCCAUGUGGUCUCGGACCAGGUCUCCGCUGGCCAACGUUCAACUCGCAUACUGAAGGCUCUCACAAACGAGACUUGAGUCGACCAUACAUCGACCGAGUCAGGAGCUGUCUUACGGCUAAGAAAAUUGACUUACUCUCGUGGUUCUCAGAAAACGGUCGCCAGCCCAAGAAAUAUCGGGAGCGGUCGGCCCAACACCCGUGUAGUCUCGCAUCCUGCGCGGCACCAAGUCGGGAACGAAUACGCAAUCGUCCUCUAUAUAGUAGAUCGGAACUGCCUCGGGAAACAGGGAACGAGACUCGUAUGGGAUUUAGGGAAUCUUUUCGGGCUCCGCCCAUUAUCUCAAGCGGCCAGCACCGCUCCUGUCCAACUAUGCACACUGUUAAUGACCCCGUGAGCCGUGGUUGUUCGCUUAAUACGUAUUUGCGAGUAGCGUAUAUCUGCGCUCUCAAGGUGGGCCUCGCUGAGCGCCCCGGGUCUGAGACGAAUAAGGCAAUAAUCGAAUUGGUCUCUCGCUCAGUGUAUCAGCGCUACCUUUGCGUUCCACGUCAAUCCGGUCUGGACGUUCUCGGCCCAUUUGAACAAAGAGACUCGCUAUGUUUUCUCCCGUAUCAUGGUAUCGCAAGGGCUAUUCCGUCAGCUACACUUAGAGAACCUCAUCUGCUCCUCCGACGUCACGGUGCACCGAAGGGGGGUUGGUAUGAUAUCUACGGGACCUUCGCAGAUACGAAAGGACCCGUUUACGAAGAUAGGGAGAGGGGAGCUCCCUAUAUGGUGGCUACGGAGUGUUCGCGCAGCAUACCUGUUACAUUGCUUUCCACACGAAUACAGAUGAUAACGCCCGAACUUGUUACCCUACCUUCACGCCCCUAUCGACAUCCUCAGUACCUUACAAAAUUUUCAGACAACCUGUCCCCUCUGUGCGAGGUUCCCCCGCUCCUAGCGAUCCUCCGUAAAUCCCGUUAUGCCCGCUGCGCGAUGUUGGGGAGAAUAGAAGCAGUGGGAGUCAUUGGCCGUAGAGAAACCGUGGUUCCGAGGCUUCCACAAACCACUAUCUCGAACCAACAGUUCGACCGUAGCCACUGCUCCCACUAUGGGGAGCUGCCAAAAACUUAUCCAGUGUCAUUGAUAAGCAUAAUAAAGUCGGACCACGUCAGCACUUCCGUGAUAUUUGCCGUCCUCUCUGGUAGGUAUCCCCCGGGUUCAGCGUCUUGUCUUACGCUCUUCGUCAACGUAAUGGCGAACAUUACAAUUACGAAACUUACUGGCCGGCUACCGGCGGCCGUCGUCAUCCCGAGAAACUGCCACGUCAUACCACGACCUUCGACACAUUUAAGGUGUCACGAUAAUUUUCCGGCUUUGUCUGACUGGGAUAUUGCAACGAACAUUCCUGGAUUCGCCAGUUCCUUUAUGUCGAAGACCGACUCUUGGCGGUUGUCCGCCAGUGACCAGCCACGGAUCCGGGGGGGAGAACUUAUCUUCGAGUUAUCGGCCGCCUUUGACGACAAACAGCUAGAAGUUGUCUCUUCCAAGUGUGUAUUAACAGAAGCAAACCGCAAUAGCGGCUAUAACAUGAGGGGAUGUGGCCUGGUCACUUACAAGAUGGUAAAGUCGUUAAUACAAAUGCCCACUAUGCACCUUAUGCGGGGGAACUCGCUACUAUAUCGACGACUCCAGUUUCUGUGCGAAAAAACCAGUCGCCUAGUCUCUUUCUCAUUUCCGGUCAUACGUACUUCAGAGAUAUACCGUGGGGAUGUUAAACCGCUGCAGUACCUACUAUUAUAUUUGAACAUCGCUGUUCACCGAGAGCGGCCGAACGUGGCCUUCAGAAUAAGGGCUCCCGCUCUCACCCGGUCUUACCCGUUUGGGACGGGGGGCGACCCGAACAGAUAUGCGUUGCUGACCCAUUCAGCUGUUUUAAGGAGAACAGCAGAGCUGGGGACAAGAAUCAUGUUGUGUGCGCACCGGACCAGUGACAGAGACCGCCCGCUCAUAACGCCGCACAACGACCCUUGUCACGGUCACACCUUAGUUCUGGUGAUCCCCCCCUACGGAGGCACCUUCUUGAUAUGUCCCGAAGGAAUUUGCAGGGUACUAGGUGGGACCUAUACUCCGUCGACCGCGUGGCAGACAUGGGCCUUACUGAACCAGUACCCGGAUCCUAGAAGCCGACGGUCCGUAUACAGCUCAUACAUAACCCCUACACGUGAGUUUCUAGCAACGGGUAGUGAAGCUAGGCGGAAUUCUGCCGCACAAUCUAUAGCAACAAUUGGCAGUGCGUCGAAGCCCCUUUACCCCGGGAUUAAACGCGUCUACAAGGGAGGGUGCCUUGCAGACGGAUACCCAUUGCAAGGCUACAUGUUUACUCCCAGCGUCUGUAUUGCAAAAUGCGAGUGCUUACGUCCGGAUCCUCAGACAAUGACCUCCAGGAUGUACGUUAGCGCGGCUCGCGGCUCCUGGGAGUCGUGUGGAUGUGUUUCACAGUCUCUACACAGUGGGGUACUACCGGGAUUAUCGGUCCGUUCUACGGCUUUAAAGCGCGUAGAUAAAACCGUCGCUGUGAUGUCAACGACGCAACCUCCUAAAUUGACUGACGAUAAUGACAGCGUCUUAACACGCCCUAGGCUUCCGGGGCUCCGAUUGCGACCCGGUCCCGGUUUGAUUCUGAAUACGCUGCCUGGAGUUCAGCCCCCAGACGUAAUUCGUAAUGGCGUCUUCGUUGCCCCAACAUUUCUCUAUCGCUCACUAGGCACACCGUCGCCGCUCGAAGAAAACUCAGGUCGUUACCCCUCUCUCAGCAUGCGUUGCAUCCGGACCAAUACGGCGCAGCAAGCGCAACACGGAGGUUCAUAUCCCAUGUGCGCCUCCUUGUGCGGCUCGGUCGUGUCGCAUGAAUCGUUAUUUGCGCACGAACAACGUAUCAUCCUUCGGCAUCGAACAUGGGUACGGUCUUCCUAUCACACUAAACUGAUUAUAGACGUGGACAUGUGGGAACAACGCGCCCGAUGCGGCAGAGAGUAUAAUCCCGUGCUUUGGAAGGUAUCGCGGGAGAGGCACCGGAUCGGUCGUGCGCUGGCUCAACUUGCUCAAUUCCGGAGAGGGAGGUCGGUACAAGGCGACCAGGGGCCUUGCGAUGUCUUGACACUGGCAGUCCUGGCGGGGGCACAAACGCCAAGUUUUACGACUCUCAGGAAACCGCUAAUAGGAACUAAUACGUCAUACGAACUUGCAGUUGUUCGGGCUGUCAGGUAUCUCAAAUCCACCAACCGCACGAUAUACCCUCCAAUAAAACGAUUAUUACGUGCCACCAAGCGGGUCCAGUGUUUGCGCACGUGGAGAACUUAUCGGGGUCGAUACGACUCAAGCUGGAGCGAGAACGCUUUAGAGCCCGAAACCUCUUCCCCAAGCGUUCUAUGUCCAGUCCCGUCCUUGAACCCCUGUUGCAGAUCUGGGCAAAAACCUACGUUAGACGGGACGACCGUUGCGCUCGAUAUUACAGUUACAAGAUCAGAGAAGGGACAGGGCUUUUCUGGUCUUUAUCCCUCUCUGAUCACUUAUCGUGUCACGAAACCAAAUGAGCUCAUUCCUCGGCAGUAUCCCAAUAAUUGCAGUAGCUUUCCGAGGGCACAUAUGGUAUUUAAUUUUGGCGCCGGCUGUUUCAGCGACGGUGGUAAGCCCUCGUCUAGAAGGAUCCGCGACAUUUUUUCCUCGUACAAGUUACUAUCGUAUCCUCAACAUAAUUACCACAUCGCUUACGGAUGCCGGUGUUCCAUGGAGUUCCGCUUACCUGCAUCACGUGACUACAACGUCACUGUGCCGGCGUACCUGCGCGUUAGCCCUAACAGCACUAAACUAAGCCCUUUCAAUACCCGUUUCGCGACUUGGGCCCGGUCACUCCUCCAUAUUUCAUACGGACCUGUAAGUUGGCCGGUUUCUCCGGGUCGUCUAGUGGAGGGGCAGUGGCCUGCUAGUAGACAAAACACCCUACCAUCUCUAGUGUGCCCGUAUCUUCUCCCUCUGGGGGGUGGUGUGGGUGCAAGCUGGUUUUGGUUUCGCACGGUUAAGGGGAUUCCUGUGUACAUGCCAGAAUCUGCGAAGAAUCGCUUUGGUGUUAUGACCGUGGUGACUUAUUUUUACUAUUCGGAUGACCUCUUGCGCACUACCUGUCACGGUGAUCUUCACACGCGAUUGUUAGGGGAGUCGGUCGAUGCCCUAUCCGGGGAGUCUCGCCGUAUACACUUAAUUCGCCGGGAAUUAUUUCGGACACGGCAAUGGACACUUUGGCUAUCACCCGCUGGAAAAGGUAGGCCUCGGGAAACCGCGUGUAUUCGGUAUCUCCUAGUCUGCCUGUUAGCGUUCCGUUCGAGGUUAAUGUACCCCUUACGAAAUAAUGUCGCACGAACGGAAUGCAGCAUUCACGAAUAUCACUUCGUAUGUUUCAUAAGAUCGAAUUCGUCCGGAUUUAUUAGAUUUGAAACUCGAGGCCCCAAUGAAAGAGAUGCCUCGAAUGUUCCAGGUCCUGAACAGGUUAGCCACCAAGCUAACGCACUAGAGGGAAACGUCAAGGUAUCAGAUGUGCCUUUUAACAUGAUUCGCGUGAUAAACUGCUCCAACAGGAACGGUGACAACUUAUAUACCCUCUAUCAAAGACGAGCAUGUUCAGGUUUGUUCCAGCCCAUCCACAGGCAGUCAAGUCCCCCAAUGGGGCUCAAGACCAGGGUCACAGGUACAGGGGAUGGCAUAAAAGAACGCUCCAUUGUUUGUGCCCGGAAUGCGUAUGUUGGGAUAACUGAUCCAGUGAAAACAGUUCGAGGAGAAGGCCGACAGGGAGUACUGGCGGCAUUACCGCUACCCGUGCCGUUGUUGCCCCGUUGCAGAACUCAUAUUCUCACUCGGUCAGUCGGAUGGUGCGCCACAUCACAUACAGAACAAACAUUUGCGCUUCCUGUAGGCAAUUUGCGGUUGCCAAAUUACGAAACAUCGCUGGGCGGUACCGCGCUAGACGACCGUCGUGAGGGAUUCGCCCGGCGGCAUCCGUACGACAAAUCGGUGUCCUCUUUGGCGAGACAAGCCGGGCCCCUAGGAGACCUCUACGCGUUCAUGUCCAUUAGGGGGCCAAACUCGAGGUGUCCUCGUAGUAGCUUCCAAUUUCUGGAAAAGCAGGUGAGCUGGUCGGCCCAAAUAGGACGGUUUGUAAAGAACCCUAUAAUGCCUCCCUUUGACAUAGGACAGGUUAAUCGUGGCCGUAAAAUGAAUCGUUCGGGGAUAACGGGCGACCAGAACAGUCCUCAGUCAGCUUUAGCUAGCGAACGUAUAUGGCCGUACGAUGCUCGAGCCCCCGCGGCUUGCAGCCUUCGGCAGUCAUGCCUCCACGACGAGAGGACCCAUCGUACCGGUGAGACAGCACUCGAUUUUGUCCGCAGGUGUUUCAUAGUCGGUUGCAGGUCUGUUAACACUUUCCCCCUGCGUUUAAGGCGUUACGGCGAGUCGGGCUGUCCCAUUUCAAGUACCCCCGAACGCCAAGGAAUGAAAAGUGGCGAUCACGCAGUUUCGUUUUAUGGGUCUGAUGAAUGGAACCUGGCCUCCUACCGCAUGCCCCAGGUGAAUGGGCCAAUUUCAUGUGUCUUCUUGGAGAAACCAGAGAAGAAACCUAACCUGUUUUGCUCAGUGAAGUCCGCUCACGGAGUCGAAGGGCAACAAUAUGUUUACGUGUGUAUCUCAGAACUCUACAGCUACCUCUCGGUUCGCGCGACAUGCCAGCCAUACCACGGGCCAUUCCCCUGCACGGUGGGAACAAAAGGUUACUCGAUUACCGCUAUCACGCAAGCCCACAUCGCGUAUGAAAUUAGUCACACUAAUGGUCUUCGGUCGAAUUUAGUCAGGACUCUAGAUUGUACCUUACGUAACUAUUCUAGGAUACCGAAAGGCUACCUCGUGCAAGGGGGGUCGUCUCCUUGCCUUGACUUCCCUUCACACCCGCUCAGAGUUACGUCAGUCCGAGUAUGCUCUGGCGAGCCCGGUUUCAGUCUGUUUAUAGGGCCUCCGAUGGGACACUCCAUGGGCCACGGGAUGUCUAUCGGGGAGAGAUUACCGAAGGUCUUGCCCCGACUACGACCCGCUUGUCUUCUGCGCUUUCUCGCGGAAGAAAACCACGCCGGCCGCACGACAACAGGUGGAAGCUGUGAUACUUUCCAAUUAAGUUAUACGGAAAAUAUAAGCCUGUCGGUAAGAAUCAGAAGACCCGCGUGUCCUUAUCACAGGGAUCGGUCGUUGAAUCCCAUCAUCCGCGGUAGCUUAAUGAGCAAUCAUAAGGGCCGACGUACCAAGUACAAUUCACAGCGAGCUAGAAACAUAUGUCCUAACUGCUCCCGAACCCAUACUUGUUUGGCCUCGUUCCCUUGGCAACUGACUCGAAGAAUGUCCGUAGUCAUAUGCUUCCAUGAAUCUGGUUGCUCGAUAGCGACUAUGAUCUUAGGCUUUCGGGCGGGCGCUUUGGAUCUACUAGUAGGACGACCAAAGCACGGGUUGCGUAGAACUGUGUUAGAAACCAAAAGGGUAUCAAGCACUCGAAGGCAAUUAGGCCAGAGUUCCGUCCCUUCUGAUAUAUCUGGGCCUCUGUCCAACAUACAUGCCACAAGUCGCGAGUCGAACGGCGCUUCCUUAAGCUCUAGGCCAAAUGGGAGUUUUCAGCAUUUACCCGUCUGUACGAUGCAUCACCUUCGGACGUUGAAGUCAACAGCCCGAUCCAACAGAGCUUCAAUGAGAAAGUCACACCCUGAGGACGCGGGAGUAUGUAAACAGCCCUAUAACAUUAAUCCAAAGUCUCCAAACUGUUCGCACUUUAUCACACCAACCAUAAUGCCUAUAUUCGAGAAGGAACGCCACAUAUCCGAGCGUAGCGAGCCUCCAAGUAAGAUUCCUCACGGAGUUAACGUACUGAAUCCUGAUUCUCCGGAUAUAGCCUACUUUACUUGCCGUUUUAGGCAGCGGGAAACGGCAAGUCACUAUCACGACAACGUCUGCCCCGACUACUCACCUACAUCGUGGCAAGACCGGUGGCUCGAUCCUUGGAUUUGCCGACUUAGCGAAGCGGGCGUCUGGGACCACAAGCUCAAGCCGUCGCCAGACAAACUUAGGGGACAACCAGAGCCAGCUCGUAUUGGACGCGUGAGGGCCCGCACCAACGUAUACGAUCGACGGCGCGAUCCGCUGUCCCGGAAAGAAAACCAAAGUACUGUACCAGCAAUAAACCCGGGAGUACUGUUCUUUUCACAUAACCCCAGCUAUCAUGGGCUAGACUACGGCCCCAGACAGGACCAACCUUAUAUUCUCCAUAACGACUCUUUCAGCGAAGUCCAGAUAGCAGGGCAACACUUUCCCAGUACUGGAGCUUCGUAUACCCCGCGUUACCCCGCUCUAACCCGUUCCACGCUACAUGCACGUAAUUUCCGGUACAGACUUCUGCGAGAUCGCAUUCCCCCAUACGGAGCAACCCCGGGAGUCCAGACGCGUAUAAGAGGCGCCAUGCAUGCACUGAUUAUGAUAGGGACUUGCCUUCUUUUACACUACUUGCACUCACUAGUUUCAGUCAAUUAUGGAGACGGCGCAUUCUCAAACCCAAUAUACAAGGCAUAUAUCCUGGGAUCUUGGCCUACUACGGUAGCACCGACAAUAACCACCGGCCUUGUGACGCUCUUGACGAUUAAAGACGACCCUAUAGCGAGCGUAUUUGAUUGGGGGGUACGUACAGUAUUCAGACUAGUGUAUAGCCUGGCACGGUCUCGAAACCGUGGGGAAUUGGGGGUCAUUAUUAUCCGUAACCUCUGCACAGCUGGCAACGGUUGGGCCUGUCUCAAAGGAACAAGGCGGUGGACGAGUGUAGGGCAAAACCGCGAGGAGAAAUUAGUUGUGCAAAGCGAAUACGAUCCGUCAAUGACUACUGCUGUACGGGGGAAAACACUCGGCCCAGUAUAUCGGCUUACAUACUUCUUAGCAACGUAUCAACCCCAAGAAUUCCCAGGUCGAGUGAUUCUGGAAUGGCAUGAGUCCUCAGAACCUCUGACUUUAGAAGGGGCACGUCAUAUACAUCAAAACCGAAAGGAUCGUCCGAGACGAUUCCAAUUAUGCGACUUUUACAUAGCCUCUAGGCCCGGGUGCCAGCUUAGAUGGGCCGGCUUUGUUGUACGCGGUUCCACGGCCAGCUCUAUGGCCUUUAGUAUGCGUAGCACACUAGUACUCUCAUUACGGGUUGUUUGUUUCCUUCGUUUGAGCUACGGGUUUAACAUAGCAUUACUUAAUCGAAUUUCCCUUCAACCGCUACGUCAAUGUACAGUCCUAUUACUAUACUUCAUUUGUUACACACGGCAACCUACGGGGCCCGGGGCCGUCCGUUUCGACUCUCACUACAUCGUCUACACCGCAAGGAGUUCGUCGGUAGUUAUUCUCGACAUCUACUUACCCCACAGCAUCUCGGAACAGUUCUUUUUAAAUCUCUGCAGUACGAAUAUUCGGCGCUGGACCGACUGUCUCCCCGCCGUACCGGUGCAACGGCCCGGCAUCGCCGAGACCCGGCCUGUUUAUUGCCUAGGAGACCAGCUCCGGAGGUUUAGAAGUUCCAUCUCAUGUGAAAAAUUCUCUUCCAUUCUGCUCGCAUUGCUCCCAGUGCGAGCAAUAUUCCUCUCAGCCAAGGAUAGAGCUCGAAGACGUGUCGGACUGGCAGGUGCUAGUUCUAGUGCCUAUGUCGUUCCGGUUGUACCUUGUGUACUCCUAUGUAAUUGUCUAGGAGAUCUCGACAGACUUAACGAUCGAUGGCAGCGUCCGUCCCGAUGGAGUACUGCGUCAGAUACUGCUCAGGAAACACUUUCAGUGCCUGUGAGCCCGACACAAAUUAGCCCCUACUGUCGUAAAGCAUUGGUUGCGGCCAGACGUAUGUCGGUGGUGCUAUGGAAGCUUACGGGCUAUCCUGGAGCCCCUAUGAGUUCAUAUUCAUUUUGGUACCGGCCGGUGGCGGGCUCUGUUAAUGCUUUACGGAACUCGGAGUGUCAUCGCGUCGUGGCCCCCCCGGCGGGUCGCGCGUCAGACGCGCAUUCCAUGUACCCAAAUCUACGAUAUUUACGCCCAUCUUUGAUUACGUUUGAGUCGAACUACCUGAAAAUUACAAGCGGGUGUUUAUGCUGGGGAGGUGCGUCUUCGAAGACUUGUAGUAGUCUCUUUUAUUCUUAUUUCGCCGUGAUCCGGAAGGGAUCUUGCACUGUGCAGGGCGGCAGGCGGGCUCCCUUCUGUCUAUACCGGCGAGCUCUAGUCGCCGCAGUGCUAUGGGUCGCCCUCUUGACUCGACGUCAAUGGCCAUGCUGUUACAGUUUACUUUGGGCGGCUGACAUUUUACGCUCAUUGCCGUCUGUCACGCCAACGACAUAUCCUUCGCUUCUGGAUUUCGGACUUAUCGUUAGUAACGGCGUUACCCAAAAUGGUGAGAUAGCCAGGGUUCCUAAUGACACUUUAGGCCACGUGCGAGCUGAUGGUUUAUUGCGGCGGGCAACAAGGAACCAUGAGGGUGCACGCUCCCAAUUUCCCAGUGUGCAUAAGAUUAGGUCUUUUUUCUGGGAUUUGAAAACUAUUCAUGCGGAAAAACGCCAGGGAGGGACCUAUCAUCUGUCGACCACUGCCUUAGACCCGGGAAAUGUAGGUCGCCAUAUUAUAGUUAGGUAG"
Length_Of_Codon_String = len(mRNA_string_s)
Amino_Acid_Sequence = ""

translation_start = 0
translation_stop = 3
loop_counter = 0

str = mRNA_string_s[translation_start:translation_stop]

while loop_counter < Length_Of_Codon_String :
	################################################################
	if "UUU" in str:
		Amino_Acid_Sequence += 'F'
	if "UUC" in str:
		Amino_Acid_Sequence += 'F'
	if "UUA" in str:
		Amino_Acid_Sequence += 'L'
	if "UUG" in str:
		Amino_Acid_Sequence += 'L'
    ###
	if "UCU" in str:
		Amino_Acid_Sequence += 'S'
	if "UCC" in str:
		Amino_Acid_Sequence += 'S'
	if "UCA" in str:
		Amino_Acid_Sequence += 'S'
	if "UCG" in str:
		Amino_Acid_Sequence += 'S'
    ###
	if "UAU" in str:
		Amino_Acid_Sequence += 'Y'
	if "UAC" in str:
		Amino_Acid_Sequence += 'Y'
	if "UAA" in str:
		break
	if "UAG" in str:
		break
    ###
	if "UGU" in str:
		Amino_Acid_Sequence += 'C'
	if "UGC" in str:
		Amino_Acid_Sequence += 'C'
	if "UGA" in str:
		break
	if "UGG" in str:
		Amino_Acid_Sequence += 'W'
    ################################
	if "CUU" in str:
		Amino_Acid_Sequence += 'L'
	if "CUC" in str:
		Amino_Acid_Sequence += 'L'
	if "CUA" in str:
		Amino_Acid_Sequence += 'L'
	if "CUG" in str:
		Amino_Acid_Sequence += 'L'
    ###
	if "CCU" in str:
		Amino_Acid_Sequence += 'P'
	if "CCC" in str:
		Amino_Acid_Sequence += 'P'
	if "CCA" in str:
		Amino_Acid_Sequence += 'P'
	if "CCG" in str:
		Amino_Acid_Sequence += 'P'
    ###
	if "CAU" in str:
		Amino_Acid_Sequence += 'H'
	if "CAC" in str:
		Amino_Acid_Sequence += 'H'
	if "CAA" in str:
		Amino_Acid_Sequence += 'Q'
	if "CAG" in str:
		Amino_Acid_Sequence += 'Q'
    ###
	if "CGU" in str:
		Amino_Acid_Sequence += 'R'
	if "CGC" in str:
		Amino_Acid_Sequence += 'R'
	if "CGA" in str:
		Amino_Acid_Sequence += 'R'
	if "CGG" in str:
		Amino_Acid_Sequence += 'R'
    ################################
	if "AUU" in str:
		Amino_Acid_Sequence += 'I'
	if "AUC" in str:
		Amino_Acid_Sequence += 'I'
	if "AUA" in str:
		Amino_Acid_Sequence += 'I'
	if "AUG" in str:
		Amino_Acid_Sequence += 'M'
    ###
	if "ACU" in str:
		Amino_Acid_Sequence += 'T'
	if "ACC" in str:
		Amino_Acid_Sequence += 'T'
	if "ACA" in str:
		Amino_Acid_Sequence += 'T'
	if "ACG" in str:
		Amino_Acid_Sequence += 'T'
    ###
	if "AAU" in str:
		Amino_Acid_Sequence += 'N'
	if "AAC" in str:
		Amino_Acid_Sequence += 'N'
	if "AAA" in str:
		Amino_Acid_Sequence += 'K'
	if "AAG" in str:
		Amino_Acid_Sequence += 'K'
    ###
	if "AGU" in str:
		Amino_Acid_Sequence += 'S'
	if "AGC" in str:
		Amino_Acid_Sequence += 'S'
	if "AGA" in str:
		Amino_Acid_Sequence += 'R'
	if "AGG" in str:
		Amino_Acid_Sequence += 'R'
    ################################
	if "GUU" in str:
		Amino_Acid_Sequence += 'V'
	if "GUC" in str:
		Amino_Acid_Sequence += 'V'
	if "GUA" in str:
		Amino_Acid_Sequence += 'V'
	if "GUG" in str:
		Amino_Acid_Sequence += 'V'
    ###
	if "GCU" in str:
		Amino_Acid_Sequence += 'A'
	if "GCC" in str:
		Amino_Acid_Sequence += 'A'
	if "GCA" in str:
		Amino_Acid_Sequence += 'A'
	if "GCG" in str:
		Amino_Acid_Sequence += 'A'
    ###
	if "GAU" in str:
		Amino_Acid_Sequence += 'D'
	if "GAC" in str:
		Amino_Acid_Sequence += 'D'
	if "GAA" in str:
		Amino_Acid_Sequence += 'E'
	if "GAG" in str:
		Amino_Acid_Sequence += 'E'
    ###
	if "GGU" in str:
		Amino_Acid_Sequence += 'G'
	if "GGC" in str:
		Amino_Acid_Sequence += 'G'
	if "GGA" in str:
		Amino_Acid_Sequence += 'G'
	if "GGG" in str:
		Amino_Acid_Sequence += 'G'
    ################################

	translation_start += 3
	translation_stop += 3
	str = mRNA_string_s[translation_start:translation_stop]
	loop_counter += 1

print(Amino_Acid_Sequence)